# TODO: generate keys and update creation rules dynamically on nixos-anywhere install (update yaml with yq)
keys:
  - &master age1nww8elvlr7l2sn2452z6wef8tyex53ehrypemkxhzfay2t99x52scwsw94
  - &luna_shorty age1j3xmhg63j8xulauzaqy5ndu4rsvmy6r287mg8aa3ehsfuzdppcfq6y6r7c
creation_rules:
  - path_regex: hosts/shared/secrets/.*
    key_groups:
      - age:
        - *master
        - *luna_shorty
  - path_regex: hosts/luna/secrets/.*
    key_groups:
      - age:
        - *master
        - *luna_shorty
  - path_regex: users/shorty/secrets/.*
    key_groups:
      - age:
        - *master
        - *luna_shorty
