# TODO: generate keys and update creation rules dynamically on nixos-anywhere install (update yaml with yq)
# the /etc/ssh/ssh_host_ed25519_key is used in nixos-config by default and needs to be added in order for
# # it to be able to succesfully complete the installation.
keys:
  - &master age1nww8elvlr7l2sn2452z6wef8tyex53ehrypemkxhzfay2t99x52scwsw94
  - &luna_shorty age10a049meemjvgdgukx6zu5lwu82mqul83l7fyd66tzy9sm8637s7q07ujez
creation_rules:
  - path_regex: hosts/shared/secrets/.*
    key_groups:
      - age:
        - *master
        - *luna_shorty
  - path_regex: hosts/luna/secrets/.*
    key_groups:
      - age:
        - *master
        - *luna_shorty
  - path_regex: users/shorty/secrets/.*
    key_groups:
      - age:
        - *master
        - *luna_shorty
