# TODO: generate keys and update creation rules dynamically on nixos-anywhere install (update yaml with yq)
# the /etc/ssh/ssh_host_ed25519_key is used in nixos-config by default and needs to be added in order for
# # it to be able to succesfully complete the installation.
keys:
  - &master age1nww8elvlr7l2sn2452z6wef8tyex53ehrypemkxhzfay2t99x52scwsw94
  - &luna_shorty age10a049meemjvgdgukx6zu5lwu82mqul83l7fyd66tzy9sm8637s7q07ujez
  - &mars_shorty age1pztum0c6dy94ah2rcwfd983hwhg8mwum3uljpwguu8cypxrs0uxsqz6hc5
  - &host_mars age1gx9hqvsc2ewy5yu4xp6v9wl0la7s9qhnezaya54yhsx3w7w3vg9s8pzknr
  - &host_luna age1pueehhjrvwh8v50u7hhpy0u7zx50nj0u7c9hgtzrr7ja0hed9qdsk0m66j
creation_rules:
  - path_regex: hosts/shared/secrets/.*
    key_groups:
      - age:
          - *master
          - *luna_shorty
          - *mars_shorty
          - *host_luna
  - path_regex: hosts/luna/secrets/.*
    key_groups:
      - age:
          - *master
          - *luna_shorty
  - path_regex: users/shorty/secrets/.*
    key_groups:
      - age:
          - *master
          - *luna_shorty
          - *host_mars
  - path_regex: hosts/mars/secrets/.*
    key_groups:
      - age:
          - *master
          - *luna_shorty
          - *mars_shorty
  - path_regex: hosts/mars/users/shorty/secrets/.*
    key_groups:
      - age:
          - *master
          - *luna_shorty
          - *mars_shorty
  - path_regex: hosts/luna/.*/secrets/.*
    key_groups:
      - age:
          - *master
          - *host_luna
