
keys:
  - &master age1hy523tlslqas8qgs0lxgxanp9gx06fjekn608w4qf66mxkjzmucqh0g6vg
  - &host_luna age10a049meemjvgdgukx6zu5lwu82mqul83l7fyd66tzy9sm8637s7q07ujez
  - &host_mars age1epkfxmjk0tlne8rmxqq77u06q3lnf5xfjcrwq42nuasswefndyfscw84cy
creation_rules:
  - path_regex: hosts/shared/secrets/.*
    key_groups:
      - age:
          - *master
          - *host_luna
          - *host_mars
  - path_regex: hosts/luna/.*/secrets/.*
    key_groups:
      - age:
          - *master
          - *host_luna
  - path_regex: hosts/mars/.*/secrets/.*
    key_groups:
      - age:
          - *master
          - *host_mars
