#!/usr/bin/env sh

set -eu

HOST=$(uname -n)
USERNAME=$(id -un)
VERBOSE=0

. ./scripts/sops.sh
. ./scripts/ssh.sh

show_help() {
  cat <<EOF
Usage: $0 [OPTION] [ARGUMENT]

Options:
  -h, -?, --help  Show this help message
  -v, --verbose   Enable verbose mode

Commands:
  help            Show this help message
  deploy          Remotely install a new NixOS system using nixos-anywhere

Examples:
  $0 --help
EOF
}

while [ $# -gt 0 ]; do
  case "$1" in
  "-v" | "--VERBOSE")
    VERBOSE=1
    ;;
  "-h" | "-?" | "--help")
    show_help
    exit 0
    ;;
  --)
    shift
    break
    ;;
  *) break ;;
  esac
  shift
done

# ---

WORKDIR=$(mktemp -d)

menu_install() {
  echo "Enter target host IP address: "
  read HOST_IP
  echo "Enter hostname: "
  read HOST
  echo "Enter username: "
  read USERNAME
}

nixos_install() {
  nix run github:nix-community/nixos-anywhere -- \
    --generate-hardware-config nixos-generate-config "./hosts/${HOST}/hardware-configuration.nix" \
    --extra-files "$WORKDIR" \
    --flake ".#${HOST}" \
    "root@${HOST_IP}"
}

# ---

case "${1-help}" in
"help")
  show_help
  ;;
"deploy")
  menu_install

  ssh_generate_host_ssh_key

  sops_create_or_update_public_age_key "host_${HOST}" "$(ssh-to-age <"${WORKDIR}/etc/ssh/ssh_host_ed25519_key.pub")"

  sops_add_host_creation_rules "hosts/${HOST}/secrets/.*"

  sops_add_user_creation_rules "host_${HOST}"

  sops_rekey

  # nixos_install

  exit 0
  ;;
esac
